name: Upload Artifact
description: Archive the build as an artifact
runs:
  using: "composite"
  steps:
    - name: Archive Build as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-build
        path: out
